"""add_cancellation_reason_and_notes

Revision ID: c12a5f168130
Revises: 2028d8d862f7
Create Date: 2026-07-31 14:50:33.391568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12a5f168130'
down_revision: Union[str, None] = '2028d8d862f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'cancellation_reason')
    # ### end Alembic commands ###
